site_name: My Docs

theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Ejemplo 3 : Ejemplo_3_Interrupts/Ejemplo_3.md
  - Ejemplo 4 : Ejemplo_4_Verilog/Ejemplo_4.md
  - Ejemplo 6 : Ejemplo_6_DDR/Ejemplo_6.md
  - Ejemplo 7 : Ejemplo_7_VGA/Ejemplo_7.md
plugins:
  - search
  - caption:
      figure:
        caption_prefix: 'Figura {index}:'
        reference_text: 'figura {index}'
      table:
        caption_prefix: 'Tabla {index}:'
        reference_text: 'tabla {index}'
